spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.aid.train.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE